-- One row per request made through the unified text, vision, or image model client.
-- This deliberately excludes prompts, images, endpoints, and credentials.
CREATE TABLE IF NOT EXISTS model_call_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID REFERENCES users(id) ON DELETE SET NULL,
    billing_mode   TEXT NOT NULL DEFAULT 'platform_credits',
    model_id       TEXT NOT NULL,
    model_name     TEXT NOT NULL DEFAULT '',
    model_category TEXT NOT NULL DEFAULT 'other',
    provider       TEXT NOT NULL DEFAULT '',
    success        BOOLEAN NOT NULL,
    duration_ms    INTEGER,
    error_message  TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_model_call_logs_created_at
    ON model_call_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_model_call_logs_user_created_at
    ON model_call_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_model_call_logs_billing_created_at
    ON model_call_logs (billing_mode, created_at DESC);

-- Preserve a useful historical baseline. New requests are recorded at the
-- individual model-call level by the application; old task rows can only
-- represent one completed or failed task each.
INSERT INTO model_call_logs (
    user_id, billing_mode, model_id, model_name, model_category,
    provider, success, duration_ms, error_message, created_at
)
SELECT
    t.user_id,
    COALESCE(u.billing_mode, 'platform_credits'),
    COALESCE(NULLIF(t.model_id, ''), 'unknown'),
    COALESCE(NULLIF(m.name, ''), NULLIF(t.model_id, ''), 'unknown'),
    COALESCE(NULLIF(m.category, ''), 'other'),
    COALESCE(m.provider, ''),
    t.status = 'completed',
    t.duration_ms,
    CASE WHEN t.status = 'completed' THEN NULL ELSE LEFT(COALESCE(t.error, ''), 500) END,
    t.created_at
FROM tasks t
LEFT JOIN users u ON u.id = t.user_id
LEFT JOIN ai_models m ON m.id = t.model_id
WHERE t.status IN ('completed', 'failed', 'cancelled');
