INSERT INTO creative_style_presets (
    id, name, module, description, prompt_template, style_hint, tags,
    preview_url, source_name, source_url, enabled, sort_order,
    schema_version, revision, execution_adapter, execution_instructions,
    input_contract, constraints, default_params, show_in_gallery
) VALUES (
    'high-concept-mythic-cinema',
    '高概念玄幻电影',
    'TEXT_TO_IMAGE',
    '把任意主题转化为拥有史诗尺度、单一奇观、强材质对比和电影摄影纪律的原创世界。无需提示词也可直接生成。',
    '先从主题、参考图或默认命题中提炼一个可用一句话复述的世界规则，再选择唯一主奇观、唯一行动主体和唯一暖色能量源。构图建立前景尺度参照、中景行动与远景巨构；使用高反差硬光、体积云或真实环境光，主色限制为低饱和钢蓝、炭黑、灰绿或沙尘色，并只允许一处橙色、赭黄或深红暖色。材质必须具有风化金属、岩层、织物、氧化表面、尘埃或胶片颗粒等可触摸细节。按题材选择 35mm、50mm 变形镜头或高位俯视镜头，保持真实景深、镜头光晕和电影级调色。用户没有输入时，默认生成风暴云海上方的古老行星神殿与归来的荒漠骑手。',
    '禁止霓虹堆叠、卡通、现有影视游戏 IP、光滑玩具塑料、装饰性对称、无意义发光线路、过饱和色彩、文字、商标和水印。',
    ARRAY['高概念', '玄幻', '电影感', '史诗场景'],
    '/creative-library/high-concept-cosmic-vortex.webp',
    'PixelScribe 高概念实验室',
    '',
    TRUE,
    1,
    2,
    1,
    'image_generate',
    '执行高概念玄幻电影视觉系统：先锁定一句话世界规则、唯一主奇观和唯一行动主体。构图同时包含尺度参照、可触摸材质和电影摄影机位；使用低饱和冷色主调，仅允许一处暖色能量或实用光源。参考图只用于主体身份或结构，不复制其中的文字、商标和现有 IP。用户未提供任何输入时，直接按默认世界命题完成一版可用结果。',
    '{"prompt":{"required":false,"max_length":4000},"images":{"min":0,"max":4,"roles":["reference"],"mime":["image/jpeg","image/png","image/webp"]}}'::jsonb,
    '{"guardrails":["先锁定一句话世界规则、唯一主奇观和唯一行动主体，再开始生成","保持低饱和冷色主调，仅允许一处暖色能量或实用光源","构图必须同时包含尺度参照、可触摸材质和电影摄影机位","参考图只用于主体身份或结构，不复制其中的文字、商标和现有 IP"],"user_overrides":["output_resolution","image_quality","aspect_ratio"],"max_outputs":1}'::jsonb,
    '{"output_resolution":"2k","image_quality":"high","aspect_ratio":"16:9","count":1}'::jsonb,
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    module = EXCLUDED.module,
    description = EXCLUDED.description,
    prompt_template = EXCLUDED.prompt_template,
    style_hint = EXCLUDED.style_hint,
    tags = EXCLUDED.tags,
    preview_url = EXCLUDED.preview_url,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    schema_version = EXCLUDED.schema_version,
    revision = EXCLUDED.revision,
    execution_adapter = EXCLUDED.execution_adapter,
    execution_instructions = EXCLUDED.execution_instructions,
    input_contract = EXCLUDED.input_contract,
    constraints = EXCLUDED.constraints,
    default_params = EXCLUDED.default_params,
    show_in_gallery = EXCLUDED.show_in_gallery,
    updated_at = NOW();
