import type { CSSProperties } from 'react'
import {
  ArchiveRestore,
  BadgeCheck,
  BarChart3,
  Bell,
  BrainCircuit,
  Braces,
  CalendarDays,
  CalendarX,
  ChartPie,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock3,
  CloudUpload,
  Coins,
  CreditCard,
  Database,
  Download,
  Eye,
  FolderCheck,
  History,
  Image as ImageIcon,
  Info,
  Landmark,
  Laptop,
  Layers3,
  LayoutDashboard,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Monitor,
  PawPrint,
  Pencil,
  Plus,
  Puzzle,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Tag,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TriangleAlert,
  Users,
  Wallet,
  Wifi,
  X,
  Zap,
  Presentation,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  add: Plus,
  add_circle: Plus,
  admin_panel_settings: ShieldCheck,
  api: Braces,
  auto_awesome: Sparkles,
  backup: ArchiveRestore,
  bar_chart: BarChart3,
  bolt: Zap,
  campaign: Megaphone,
  chat: MessageSquare,
  chat_bubble_outline: MessageCircle,
  check_circle: CircleCheck,
  close: X,
  cloud_upload: CloudUpload,
  dashboard: LayoutDashboard,
  database: Database,
  delete: Trash2,
  delete_forever: Trash2,
  delete_sweep: Trash2,
  desktop_windows: Monitor,
  donut_large: ChartPie,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  event_busy: CalendarX,
  extension: Puzzle,
  group: Users,
  history: History,
  image: ImageIcon,
  info: Info,
  laptop_mac: Laptop,
  layers: Layers3,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  mark_email_read: MailCheck,
  model_training: BrainCircuit,
  notifications: Bell,
  network_check: Wifi,
  payments: CreditCard,
  pending_actions: Clock3,
  pets: PawPrint,
  progress_activity: LoaderCircle,
  psychology: BrainCircuit,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  restore: RotateCcw,
  rule_folder: FolderCheck,
  save: Save,
  schedule: Clock3,
  search: Search,
  sell: Tag,
  settings: Settings,
  shield: Shield,
  shield_lock: ShieldCheck,
  star: Star,
  star_border: Star,
  slideshow: Presentation,
  terminal: Terminal,
  timer: Timer,
  today: CalendarDays,
  token: Coins,
  toll: Coins,
  trending_down: TrendingDown,
  verified_user: BadgeCheck,
  visibility: Eye,
  warning: TriangleAlert,
}

type AdminIconProps = {
  name: string
  className?: string
  style?: CSSProperties
  title?: string
}

export default function AdminIcon({ name, className = '', style, title }: AdminIconProps) {
  const Icon = ICONS[name] || CircleHelp
  return (
    <Icon
      aria-hidden={title ? undefined : true}
      aria-label={title}
      className={className}
      focusable="false"
      strokeWidth={1.9}
      style={{ width: '1em', height: '1em', ...style }}
    />
  )
}
