import type { EditorMode } from './editor-store'
import type { PPTLayoutPreview } from './ppt-template-catalog'
import { EXPANDED_PUBLIC_GALLERY_PRESETS } from './public-gallery-expanded'
import { HOSTED_MEIGEN_PUBLIC_GALLERY_PRESETS } from './public-gallery-meigen-hosted'

export type PublicGalleryModule = EditorMode

export interface PublicGalleryPreset {
  id: string
  title: string
  subtitle: string
  image: string
  images?: string[]
  prompt: string
  module: PublicGalleryModule
  moduleLabel: string
  tags: string[]
  aspect: 'poster' | 'landscape' | 'square'
  author: string
  likes: number
  favorites?: number
  liked?: boolean
  favorited?: boolean
  isOwner?: boolean
  styleHint?: string
  taskId?: string
  sourceTaskId?: string
  assetId?: string
  pageCount?: number
  createdAt?: string
  isTemplate?: boolean
  templateId?: string
  layoutCount?: number
  license?: string
  sourceUrl?: string
  sourceRevision?: string
  templateLayouts?: PPTLayoutPreview[]
}

export const PUBLIC_GALLERY_PRESETS: PublicGalleryPreset[] = [
  {
    id: 'poster-george-bass-guide',
    title: '海岸徒步一日团',
    subtitle: '旅行长图 / 活动招募',
    image: '/showcase-poster-george-bass-guide.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['旅行', '活动', '长图', '编辑式排版'],
    styleHint: '高端旅行杂志排版，暖色日光、清晰路线信息、自然风景照片拼贴、精致留白。',
    prompt: '生成一组高端旅行活动海报，主题为「海岸徒步一日团」。画面需要包含海岸风景主视觉、路线亮点、集合时间、难度等级、报名入口和注意事项。整体使用旅行杂志式排版，暖色日光、清爽留白、信息层级清楚，适合作为小红书长图和线下活动招募海报。',
  },
  {
    id: 'poster-george-bass-route',
    title: '路线攻略视觉卡',
    subtitle: '路线海报 / 地图信息',
    image: '/showcase-poster-george-bass-route.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['路线', '地图', '攻略', '户外'],
    styleHint: '地图信息图 + 旅行摄影拼贴，路线节点清楚，标题强识别。',
    prompt: '设计一组徒步路线攻略海报，主题为「海岸路线完整指南」。需要展示路线地图、关键停靠点、预计耗时、补给提示、最佳拍摄点和安全提醒。视觉风格为旅行摄影拼贴结合地图信息图，标题醒目，路线节点清楚，整体高级克制，不要廉价旅游广告感。',
  },
  {
    id: 'poster-patisserie-steps',
    title: '甜品品牌故事',
    subtitle: '品牌流程 / 社媒海报',
    image: '/showcase-poster-patisserie-steps.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['甜品', '品牌', '流程', '暖色'],
    styleHint: '法式甜品店品牌视觉，奶油色纸张质感，步骤式信息卡，温柔高级。',
    prompt: '制作一组法式甜品品牌故事海报，主题为「从烘焙到分享」。用 3 到 5 个步骤展示原料、制作、装饰、包装和分享场景。画面要有奶油色纸张质感、精致甜点照片、手写感小标题和温柔暖色调，适合甜品店社媒发布和门店展示。',
  },
  {
    id: 'poster-cake-product',
    title: '节日蛋糕企划',
    subtitle: '产品海报 / 礼盒促销',
    image: '/showcase-poster-cake-product.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['产品', '节日', '蛋糕', '礼盒'],
    styleHint: '高颜值烘焙产品海报，礼盒氛围、柔光摄影、卖点卡片。',
    prompt: '生成一组节日蛋糕产品海报，突出「新鲜现烤、限定口味、礼盒包装、到店自提/配送」四个卖点。主体是一款高颜值蛋糕，搭配柔光摄影、节日礼物氛围和简洁卖点卡片，版式高级、可用于朋友圈、小红书和门店电子屏。',
  },
  {
    id: 'poster-airclean-architecture',
    title: '空气净化系统方案',
    subtitle: '方案架构 / 科技海报',
    image: '/showcase-poster-airclean-architecture.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['科技', '方案', '架构', '机器人'],
    styleHint: '产品方案架构海报，暖白背景、模块化结构、科技产品渲染。',
    prompt: '设计一组空气净化机器人方案海报，画面需要包含产品主视觉、系统架构、传感器能力、净化流程、移动路径和核心卖点。风格为高端科技产品发布会视觉，暖白背景、模块化信息结构、轻微 3D 产品渲染质感，避免过度赛博和低质按钮堆叠。',
  },
  {
    id: 'poster-smartclean-robot',
    title: '智能清洁产品卖点',
    subtitle: '科技产品 / 卖点总览',
    image: '/showcase-poster-smartclean-robot.jpg',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['科研图', '机器人', '卖点', '科技'],
    prompt: '一张高端智能清洁机器人产品宣传海报，中心是精致的白色清洁机器人产品渲染，周围用极简信息卡展示「自动规划路线、边角清洁、低噪运行、长续航、智能避障」五个卖点。暖白色高级背景，柔和棚拍光影，现代中文商业海报排版，细节清晰，适合电商首图和新品发布。',
  },
  {
    id: 'poster-atelier-men',
    title: '男装核心卖点',
    subtitle: '服装品牌 / Lookbook',
    image: '/showcase-poster-atelier-men.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['服装', '男装', '品牌', 'Lookbook'],
    styleHint: '高级男装 lookbook，杂志留白、黑白棕配色、卖点图解。',
    prompt: '制作一组高级男装品牌 Lookbook 海报，展示都市通勤男装的核心卖点：版型、面料、耐穿、搭配建议和适用场景。视觉要像精品时装杂志，黑白棕配色、克制留白、模特图与卖点图解结合，适合新品系列发布。',
  },
  {
    id: 'poster-atelier-women',
    title: '女装系列卖点',
    subtitle: '服装品牌 / 系列企划',
    image: '/showcase-poster-atelier-women.jpg',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan Seed',
    likes: 0,
    tags: ['服装', '女装', '品牌', '高级感'],
    styleHint: '高级女装系列企划，柔和自然光、编辑式排版、精致面料细节。',
    prompt: '生成一组高级女装系列企划海报，主题为「日常也有仪式感」。需要展示模特主视觉、面料细节、廓形特点、搭配建议和购买引导。风格为现代时装杂志排版，柔和自然光、米白和浅棕色调、精致留白，适合品牌上新和社媒投放。',
  },
  {
    id: 'poster-night-run',
    title: '城市夜跑社群',
    subtitle: '活动主视觉 / 运动海报',
    image: '/gallery-poster-night-run.png',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['运动', '活动', '城市夜景', '速度感'],
    styleHint: '从屋顶跑道的对角线进入，深靛蓝城市夜色与一抹亮橙色路径形成视觉动线，左上和底部保留中文信息区。',
    prompt: '设计一张夏夜城市跑步社群活动海报。画面主体是三位跑者沿屋顶跑道由右下向左上前进，背景是克制的城市天际线；用钴蓝跑道和亮橙色路径组织速度感，在左上和底部留出干净的中文标题、日期与报名信息区。画面不直接生成文字、数字、商标或水印。',
  },
  {
    id: 'poster-citrus-paper-collage',
    title: '柑橘香氛纸艺',
    subtitle: '新品发布 / 拼贴海报',
    image: '/gallery-poster-citrus-collage.png',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['新品', '香氛', '纸艺拼贴', '明亮'],
    styleHint: '用一个产品主体、纸张撕边、柑橘切片和少量星形标注建立层次，蓝黄橙三色受控使用。',
    prompt: '制作一张柑橘香氛新品海报。透明喷雾瓶立在纸艺舞台中央，橙皮切片、蓝色弧形纸片和少量手绘星形标注围绕主体；顶部与底部预留中文标题和卖点区。使用真实印刷颗粒和可见纸张边缘，画面不生成任何文字、数字、商标或水印。',
  },
  {
    id: 'poster-swiss-exhibition',
    title: '当代艺术展网格',
    subtitle: '展览视觉 / 极简海报',
    image: '/gallery-poster-swiss-grid.png',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['展览', '瑞士网格', '极简', '艺术'],
    styleHint: '以一件抽象折纸雕塑为唯一视觉中心，暖象牙色留白配极细网格，荧光酸橙只出现一次。',
    prompt: '设计一张国际当代艺术展海报。暖象牙色展墙上有一件哑光银色抽象折纸雕塑，极细黑色网格组织版面，右下仅保留一枚荧光酸橙色结构点；左侧保留大面积中文标题和场馆信息区。画面不要直接生成文字、数字、商标或水印。',
  },
  {
    id: 'poster-new-chinese-tea',
    title: '桂花茶新中式',
    subtitle: '品牌主视觉 / 产品海报',
    image: '/gallery-poster-new-chinese-tea.png',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['新中式', '茶饮', '品牌', '留白'],
    styleHint: '让真实玻璃茶杯成为主体，用水墨山形、金色月牙和桂花枝建立前后层次，顶部留白用于标题。',
    prompt: '生成一张新中式桂花茶品牌海报。透明玻璃茶杯置于深墨绿漆面台座，茶汤清澈，背景为层叠宣纸山形与一弯低调金色月牙；顶部和右侧保留清晰中文标题与卖点区域。现代克制、真实材质、无文字、无商标、无水印。',
  },
  {
    id: 'science-nanocarrier-delivery',
    title: '纳米递送机制',
    subtitle: '科研图文摘要 / 生物医学',
    image: '/gallery-science-nanocarrier.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['科研图', '生物医学', '机制图', '图文摘要'],
    prompt: '生成论文图文摘要风格的纳米颗粒递送机制图：左侧为规则排列的纳米载体，中部跨越细胞膜并进入细胞，右侧在细胞质内释放荧光载荷。用一条连续递送路径和两个克制的放大观察窗组织画面，暖白背景，青蓝、深蓝和琥珀三色，不生成文字、数字或商标。',
  },
  {
    id: 'science-flexible-battery',
    title: '柔性电池微观剖面',
    subtitle: '材料科学 / 器件结构',
    image: '/gallery-science-materials-cutaway.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['科研图', '材料', '电池', '剖面'],
    prompt: '生成材料科学图文摘要：左侧为柔性电池薄膜的三层剖面，中部放大展示离子在多孔电极中穿梭，右侧是一块弯折后仍稳定工作的柔性器件。用连续青色离子路径连接宏观和微观，暖白背景，深蓝、青绿和少量琥珀色，不生成文字、数字或商标。',
  },
  {
    id: 'science-watershed-ecosystem',
    title: '流域生态过程',
    subtitle: '环境科学 / 连续剖面',
    image: '/gallery-science-ecosystem.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['科研图', '生态', '流域', '过程图'],
    prompt: '生成环境科学研究视觉：从左侧山地森林、中部湿地到右侧城市河口形成连续流域剖面，展示雨水收集、植被过滤、水质监测与清洁水流入海。用一条蓝绿流线和两枚必要的放大观察窗组织因果过程，留白背景，不生成文字、数字或商标。',
  },
  {
    id: 'science-hydrogel-repair-concept',
    title: '水凝胶修复路径',
    subtitle: '科研图形摘要 / 概念示意',
    image: '/gallery-science-hydrogel-repair.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['科研图', '图形摘要', '医学示意', '概念路径'],
    styleHint: '科研图只表现研究设计与概念机制，不伪造显微结果、数据或可识别患者信息。',
    prompt: '生成一张原创科研图形摘要，表现非侵入性皮肤创面修复的概念路径：从左到右依次展示简洁皮肤剖面、透明水凝胶覆盖、组织结构有序修复。只保留两个细引线圆形放大窗，分别说明水凝胶微观网络与修复区域。暖白背景，医疗青绿、低饱和珊瑚、墨蓝与暖灰配色。明确为概念示意，不生成文字、数字、商标、水印、伪实验数据、真实显微图、患者身份、血腥画面、霓虹或科幻界面。',
  },
  {
    id: 'image-zine-mountain-lake',
    title: '山湖露营杂志拼贴',
    subtitle: '旅行风景 / 实景拼贴',
    image: '/gallery-zine-mountain-lake.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['风景', '旅行', '拼贴', '杂志'],
    prompt: '竖版旅行杂志拼贴：清晨高原湖畔的帐篷和背包客作为真实摄影锚点，保留远山、湖面与帐篷关系；另一侧扩展为米白纸面上的抽象岩层和云雾插画，照片与插画之间有清晰手撕纸纤维边缘，一抹钴蓝从湖岸线延续到纸面。画面不生成文字、商标或水印。',
  },
  {
    id: 'image-zine-rainy-harbor',
    title: '雨港书摊',
    subtitle: '人物旅行 / 手撕杂志拼贴',
    image: '/gallery-zine-rainy-harbor.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['人物', '海港', '杂志拼贴', '雨天'],
    styleHint: '用真实场景承担叙事，再让纸张、剪贴和铅笔线条只服务于人物的观察视角；不靠高饱和或戏剧化滤镜制造情绪。',
    prompt: '竖版手撕杂志拼贴：雨后傍晚的海港小镇，一位穿姜黄雨衣的女性站在临海旧书摊旁；保留书摊、港湾与远处屋顶的真实摄影关系，再用象牙白手撕纸、靛蓝海浪剪纸、低饱和珊瑚票根碎片和铅笔路线勾线向外延展。独立杂志质感，克制、安静，不生成文字、商标、水印或电影滤镜。',
  },
  {
    id: 'image-zine-train-journey',
    title: '雪线列车',
    subtitle: '高原旅程 / 人物观察',
    image: '/gallery-zine-train-journey.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['人物', '高原', '列车', '手撕画'],
    styleHint: '让人物、车窗与雪峰构成一个完整观察瞬间；纸面拼贴只补充路线和触感，不堆叠无关装饰。',
    prompt: '竖版手撕杂志拼贴：高原列车上，一位穿铁锈红毛衣的年轻男性望向窗外雪峰与湖泊；保留车厢、人物、湖面与山峰的真实场景，再用浅天蓝纸面、铅笔山脊线稿、苔绿邮票形状和少量手撕边缘组织版面。安静的独立旅行杂志质感，无文字、商标、水印、UI 或过度 HDR。',
  },
  {
    id: 'image-moments-solar-term',
    title: '初秋窗边苏打',
    subtitle: '朋友圈配图 / 节气生活',
    image: '/gallery-moments-solar-term.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'square',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['朋友圈', '节气', '生活方式', '静物'],
    prompt: '方形节气生活视觉：初秋清晨的窗边，透明玻璃杯中是金黄柑橘苏打，旁边有一本翻开的书、一枝桂花和布质餐巾。阳光在桌面形成克制几何光影，暖白、金黄和鼠尾草绿为主色，在右上保留安静区域供后期中文短句，画面不生成文字、商标或水印。',
  },
  {
    id: 'image-moments-photo-diary',
    title: '周末花市三格日记',
    subtitle: '朋友圈配图 / 多镜头生活记录',
    image: '/gallery-moments-photo-diary.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'square',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['朋友圈', '三格日记', '摄影', '生活方式'],
    styleHint: '用环境、局部和动作三个镜头距离讲同一件小事，不靠滤镜或贴纸堆砌氛围。',
    prompt: '制作一张方形三格生活摄影日记：第一格是午后自然光下的本地花市环境，第二格是带水珠的牛皮纸包装和一枝迷迭香细节，第三格是一双手在窗边把鲜花插进朴素陶瓶。三格共享自然光、低饱和奶油色、叶绿色与少量陶土色，留出清晰暖白间隔。真实摄影、克制编辑感，无文字、商标、水印、贴纸、人工散景或重度磨皮。',
  },
  {
    id: 'image-fantasy-cloud-market',
    title: '云朵集市奇遇',
    subtitle: '奇趣幻想 / 朋友圈配图',
    image: '/gallery-fantasy-cloud-market.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'square',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['奇趣幻想', '角色', '幻想世界', '朋友圈'],
    prompt: '方形原创奇趣幻想插画：傍晚的云朵集市漂浮在巨大蘑菇屋和暖色星球之间，一只戴红围巾的圆润小怪物骑纸飞机运送发光果实。主角动作清楚、远景简化、近景层次丰富，深青蓝天空配橙红灯光和柔粉云朵，右上留出中文短句区域，不生成文字、商标或水印。',
  },
  {
    id: 'image-comic-ip-harbor',
    title: '雾港收信处',
    subtitle: '漫剧 IP / 电影叙事分镜',
    image: '/gallery-cinema-harbor-key-art.png',
    images: ['/gallery-cinema-harbor-key-art.png', '/gallery-cinema-harbor-shot-1.png', '/gallery-cinema-harbor-shot-2.png', '/gallery-cinema-harbor-shot-3.png'],
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['漫剧IP', '角色设计', '电影感', '原创世界观'],
    prompt: '原创漫剧 IP 主视觉：雨后潮汐港口的信使少女，短深青色头发，旧米黄雨衣和帆布邮袋，正把一封朱红旧信按在胸前；身边悬浮一只半透明玉绿色灯鳐信使。先确定她尚未完成的选择、观众位置和视线流量，再用深蓝海港、暖黄航标灯与唯一朱红信封组织剧情。必须完全原创，不借用任何现有动画、漫画、游戏或影视 IP，不生成文字、商标或水印。',
  },
  {
    id: 'image-character-bible-cloud-lantern',
    title: '云灯使角色设定',
    subtitle: '原创角色 / 三视图与表情板',
    image: '/gallery-character-bible-cloud-lantern.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['原创角色', '角色设定板', '三视图', '表情'],
    styleHint: '一张完整的角色设计页应同时讲清轮廓、服装结构、表情范围、动作节奏与配色，而不是只给一张头像。',
    prompt: '制作一张原创东方幻想角色设定板：一位携带小型云灯的年轻旅行者，完整正面、侧面和背面三视图位于上方，六格不同情绪表情位于中部，下方展示四个有明确动作目的的姿态和一组材质配色样本。暖白纸面、细铜色框线、青灰与玉绿色受控使用。所有角色、道具、服装和世界观必须原创，不生成文字、商标或水印。',
  },
  {
    id: 'image-library-stairwell-documentary',
    title: '图书馆楼梯的留白',
    subtitle: '空间纪实 / 建筑摄影',
    image: '/gallery-architecture-library-stairwell.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['建筑', '空间纪实', '自然光', '极简'],
    styleHint: '把光线、材质、动线和一个微小人物动作作为叙事主体，让大量留白参与构图，而不是用装饰堆满空间。',
    prompt: '竖幅建筑纪实摄影：冬日下午，一座当代图书馆的混凝土楼梯从画面右下延伸到左上；磨砂玻璃护栏、温润木扶手与下方成排书架形成清晰层次。一位穿深色高领毛衣的人抱着几本书停在窗边，人物只占画面一小部分。使用真实建筑摄影的自然漫射光、克制灰色与木色，强调墙面肌理、台阶透视和安静留白。无文字、无商标、无水印、无人群、无夸张广角变形。',
  },
  {
    id: 'image-eastern-still-life-plum',
    title: '梅影与器物',
    subtitle: '东方生活方式 / 静物摄影',
    image: '/gallery-eastern-still-life-plum.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['东方美学', '静物', '生活方式', '自然光'],
    styleHint: '用真实材质与单向自然光建立东方日常感：器物、花枝、书页各自安静，避免滤镜化国风和堆叠符号。',
    prompt: '竖幅当代东方静物摄影：深色木桌上有一只带细小釉点的灰青色茶盏、一枝初开的白梅和一本摊开的艺术画册；侧窗投下柔和矩形光影，墙面是带细微纹理的浅灰矿物质感。前景加入一只低调陶盘和亚麻布，构图留出上半部呼吸空间。色彩为炭黑、灰青、米白与一点梅枝暖褐，强调陶器釉面、纸张纤维与安静日常。无文字、无书名、无商标、无水印、无茶道摆拍感。',
  },
  {
    id: 'image-coastal-paper-map',
    title: '海岸徒步纸雕路线',
    subtitle: '旅行攻略 / 地形纸艺',
    image: '/gallery-coastal-paper-map.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['旅行', '地形纸艺', '攻略', '杂志拼贴'],
    styleHint: '把实景窗口嵌进纸雕地形，用一个路线标记和大面积纸面留白组织攻略感，而不是把地图信息堆满画面。',
    prompt: '竖幅编辑式旅行视觉：一张当代纸雕海岸地形图，象牙白纸层勾勒海岸线，苔藓绿地形层从左侧向下延伸，一条细钴蓝海岸线贯穿画面，只放一个朱红路线点。地形中央嵌入一幅真实海崖徒步者的小型摄影窗口，远处海面和云层保持安静。材质可触摸、层级清晰、留白充足，不生成文字、编号、商标、水印、霓虹或油画质感。',
  },
  {
    id: 'image-natural-history-butterfly',
    title: '蓝蝶自然史拼贴',
    subtitle: '文章配图 / 当代博物绘',
    image: '/gallery-natural-history-butterfly.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'square',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['自然史', '文章配图', '铅笔线稿', '独立杂志'],
    styleHint: '把标本盒、描图纸、植物轮廓与一只主角蝶放在同一张纸面，让细节服务于一眼可读的主视觉。',
    prompt: '方形当代自然史编辑插画：一只矿物蓝蝴蝶停在干燥银杏叶上，旁边是一只透明玻璃标本盒、半透明描图纸上的石墨植物轮廓和两片克制的植物碎片。暖白纸面、细密石版印刷与彩铅纹理，矿物蓝、赭黄、柔炭黑和纸白为主色。构图轻盈、像独立杂志艺术指导，无文字、标签、数字、商标、水印、霓虹或陈旧猎奇标本感。',
  },
  {
    id: 'science-polymer-cycle',
    title: '高分子循环路径',
    subtitle: '科研图形摘要 / 材料循环',
    image: '/gallery-science-polymer-cycle.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['高分子', '循环经济', '机制图', '概念示意'],
    styleHint: '以单条因果路径连接宏观物件、微观链段和新材料，所有箭头只表达概念过程，不暗示真实实验数据。',
    prompt: '横版原创科研概念图形摘要，表现高分子循环利用机制：左侧透明瓶体被拆解为简化聚合物链，中部抽象酶形结构将链段分离为小型构件，右侧构件成为一张新的极简材料片。三段通过连续箭头组成单一路径，暖白背景、海洋蓝、叶绿与少量珊瑚色，编辑式信息设计与柔和纸材质。明确为概念示意，不生成文字、数字、显微图、统计图、商标、水印或伪造结果。',
  },
  {
    id: 'science-soil-carbon-cycle',
    title: '土壤碳循环剖面',
    subtitle: '环境科学 / 连续剖面',
    image: '/gallery-science-soil-carbon-cycle.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['土壤', '碳循环', '环境科学', '概念路径'],
    styleHint: '用地表、根系、土层和深层稳定组分串起一条连续过程，放大窗只用于解释关键阶段。',
    prompt: '横版原创环境科学概念图：森林冠层和根系进入分层土壤剖面，根系把有机颗粒带入土层，微生物启发的点状形态转化这些颗粒，深层形成稳定碳组分。用一条连续白色路径和三个无文字圆形放大窗解释过程。泥土红、黏土、苔藓绿、炭黑与暖白配色，清晰出版级层次。概念教学图，不生成数值、图表、显微图、商标、水印或真实测量结论。',
  },
  {
    id: 'science-organ-chip',
    title: '器官芯片双通道',
    subtitle: '生物工程 / 微流控机制',
    image: '/gallery-science-organ-chip.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['微流控', '器官芯片', '生物工程', '机制图'],
    styleHint: '让透明芯片的双通道、分隔膜和小型组织层形成一个干净可读的中心结构，避免实验室照片或真实数据暗示。',
    prompt: '横版原创微流控器官芯片概念示意：画面中央是一枚透明掌心大小芯片，两条优雅并行流体通道由多孔膜分开；左侧两种液滴进入，右侧通道汇入抽象组织层，下方一个圆形放大窗展示通道分层结构。白底、半透明琥珀色、青绿色和莓红点缀，精确等距结构与轻微深度感。不生成文字、数字、图表、显微图、患者数据、器官照片、商标、水印或实验结果。',
  },
  {
    id: 'science-cool-roofs',
    title: '城市屋顶降温机制',
    subtitle: '城市科学 / 建筑剖面',
    image: '/gallery-science-cool-roofs.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['城市科学', '屋顶', '建筑剖面', '环境机制'],
    styleHint: '把常规屋顶、绿化屋顶和浅色反射屋顶并置，用热流和气流解释差异，保持建筑信息图的克制。',
    prompt: '横版原创城市热环境概念图：并列三栋紧凑街区建筑，分别展示深色常规屋顶、植物绿化屋顶和浅色反射屋顶。透明橙到蓝色流线解释日照热量与冷却气流，底部保留树木和有阴影的人行道。砖红、叶绿、淡蓝、石墨与象牙白的建筑信息设计，不生成文字、数字、图表、地图、卫星图、商标、水印或真实测量数据。',
  },
  {
    id: 'science-photonic-sensor',
    title: '光子芯片传感路径',
    subtitle: '光学工程 / 结构示意',
    image: '/gallery-science-photonic-sensor.png',
    module: 'SCI_FIG',
    moduleLabel: '科研',
    aspect: 'landscape',
    author: 'Linggan 精选',
    likes: 0,
    tags: ['光子芯片', '传感', '波导', '工程结构'],
    styleHint: '以光路和波导分叉为唯一阅读路径，冷暗背景只衬托结构与信号，不做赛博 UI。',
    prompt: '横版原创光子传感机制图：深色哑光背景上一枚紧凑硅光芯片剖面，柔和紫色入射光从左进入，分叉经过几条精确波导，在中央透明液滴附近发生交互，右侧合成为一条琥珀色信号；右下一个圆形放大窗展示分层波导几何。克制紫、青和琥珀光线，高对比工业设计。不生成文字、数字、公式、频谱、商标、水印、UI 或伪造数据。',
  },
  {
    id: 'meigen-tang-fantasy-space',
    title: '唐风巨构空间',
    subtitle: '公开案例 / 东方幻想场景',
    image: '/gallery-meigen-tang-fantasy.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'landscape',
    author: 'MeiGen 公开案例',
    likes: 0,
    tags: ['东方幻想', '建筑', '巨构', '空间叙事'],
    sourceUrl: 'https://www.meigen.ai/prompt/2084911244310687765',
    license: '公开提示词案例',
    prompt: '以宏伟中式建筑、云海和远处巨型月亮组成东方幻想空间；使用极广视角让门洞或廊柱成为前景框景，一位女性人物仅作为尺度与视线锚点。让空旷空间、建筑秩序和远景巨物形成层次，画面保持克制留白与电影级自然光。',
  },
  {
    id: 'meigen-chili-topdown',
    title: '辣酱顶视产品摄影',
    subtitle: '公开案例 / 食品电商静物',
    image: '/gallery-meigen-chili-food.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'square',
    author: 'MeiGen 公开案例',
    likes: 0,
    tags: ['食品摄影', '电商', '顶视图', '产品静物'],
    sourceUrl: 'https://www.meigen.ai/prompt/2038456800190808446',
    license: '公开提示词案例',
    prompt: '方形顶视食品产品摄影：让一瓶辣酱作为中心锚点，番茄、红椒、香料和一只小木勺沿着清晰节奏围绕主体分布。使用有颗粒感的暖棕台面、一块深色石板和方向明确的柔硬阴影，色彩浓郁但受控。包装文字与商标留给后期，不由模型直接生成。',
  },
  {
    id: 'meigen-dragon-material',
    title: '金属釉质生物特写',
    subtitle: '公开案例 / 材质概念设计',
    image: '/gallery-meigen-dragon-portrait.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'landscape',
    author: 'MeiGen 公开案例',
    likes: 0,
    tags: ['概念设计', '材质', '生物特写', '幻想'],
    sourceUrl: 'https://www.meigen.ai/prompt/2085078187231580355',
    license: '公开提示词案例',
    prompt: '横版原创幻想生物侧脸特写：用深青蓝釉质、金属网状鳞片和少量瓷白质地构成一种未知生物的头部表面，单只琥珀色眼睛成为焦点。背景保持潮湿岩面般的低调灰色，强调真实微表面、材质过渡和压低的戏剧光，不添加文字、标志或既有影视游戏 IP。',
  },
  {
    id: 'meigen-candy-game-world',
    title: '糖果积木游戏世界',
    subtitle: '公开案例 / 轻量 3D 插画',
    image: '/gallery-meigen-candy-game.png',
    module: 'TEXT_TO_IMAGE',
    moduleLabel: '文生图',
    aspect: 'poster',
    author: 'MeiGen 公开案例',
    likes: 0,
    tags: ['3D 插画', '游戏感', '积木', '明亮'],
    sourceUrl: 'https://www.meigen.ai/prompt/community_d276fe83-a020-4f19-a060-967daccd6934',
    license: '公开提示词案例',
    prompt: '竖幅轻量 3D 游戏插画：将彩色圆角积木搭成两个立柱，中间悬挂一台原创掌机角色，背景为干净蓝天、软云和小型几何积木地面。用明亮糖果色、软塑料材质和清楚的大形构图营造轻快感，不使用真实游戏机品牌、文字、商标或水印。',
  },
  {
    id: 'meigen-brush-portrait',
    title: '黑白笔触时尚肖像',
    subtitle: '公开案例 / 编辑式人物海报',
    image: '/gallery-meigen-fashion-editorial.png',
    module: 'POSTER_GEN',
    moduleLabel: '海报',
    aspect: 'poster',
    author: 'MeiGen 公开案例',
    likes: 0,
    tags: ['时尚肖像', '黑白', '笔触', '编辑海报'],
    sourceUrl: 'https://www.meigen.ai/prompt/2084926774992158925',
    license: '公开提示词案例',
    prompt: '竖幅编辑式人物海报：一位原创人物的黑白半身肖像居中，粗粝墨黑笔触从边缘切入，仅用一枚高饱和暖黄作为视觉断点。人物穿着极简深色造型，画面具有印刷海报的纸张颗粒与强烈明暗关系；标题、姓名和品牌信息仅预留后期排版安全区，不让模型生成小字或标志。',
  },
  ...EXPANDED_PUBLIC_GALLERY_PRESETS,
  ...HOSTED_MEIGEN_PUBLIC_GALLERY_PRESETS,
]

export const POSTER_TEMPLATE_PRESETS = PUBLIC_GALLERY_PRESETS.filter(item => item.module === 'POSTER_GEN')

export function findPublicGalleryPreset(id?: string | null) {
  if (!id) return undefined
  return PUBLIC_GALLERY_PRESETS.find(item => item.id === id)
}

export function publicGalleryModeLabel(mode: PublicGalleryModule) {
  if (mode === 'POSTER_GEN') return '海报'
  if (mode === 'PPT_GEN') return 'PPT'
  if (mode === 'SCI_FIG') return '科研'
  if (mode === 'IMAGE_EDIT') return '图片编辑'
  return '文生图'
}
